// Tipe untuk CompanySettings & UserPreferences (mirror Prisma model)

export type CompanySettings = {
  id: string;
  name: string;
  legalName: string | null;
  taxId: string | null;
  email: string | null;
  phone: string | null;
  address: string | null;
  city: string | null;
  postalCode: string | null;
  country: string;
  currencyCode: string;
  currencySymbol: string;
  currencyPosition: "before" | "after";
  decimalPlaces: number;
  thousandSeparator: string;
  decimalSeparator: string;
  locale: string;
  fiscalYearStartMonth: number;
  fiscalYearStartDay: number;
  defaultTaxRate: number;
  taxIncluded: boolean;
  ppnEnabled: boolean;
  bpjsEmployerRate?: number;
  logoUrl: string | null;
  companyCode: string;
  numberingFormat: string;
  invoicePrefix: string;
  invoiceStartNumber: number;
  nextInvoiceNumber?: number | null;
  quotePrefix?: string;
  quoteStartNumber?: number;
  nextQuoteNumber?: number;
  orderPrefix?: string;
  orderStartNumber?: number;
  nextOrderNumber?: number;
  defaultPaymentTermsDays?: number | null;
  invoiceSignature?: string | null;
  invoiceSignatureTitle?: string | null;
  invoiceFooterNote?: string | null;
  invoiceNote?: string;
  docGreeting?: string | null;
  docPicName?: string | null;
  docPicPhone?: string | null;
  invoiceBankName?: string | null;
  invoiceBankAccount?: string | null;
  invoiceBankHolder?: string | null;
  journalPrefix: string;
  journalStartNumber?: number;
  nextJournalNumber?: number;
  openingPrefix?: string;
  openingStartNumber?: number;
  nextOpeningNumber?: number;
  receiptPrefix?: string;
  receiptStartNumber?: number;
  nextReceiptNumber?: number;
  paymentPrefix?: string;
  paymentStartNumber?: number;
  nextPaymentNumber?: number;
  transferPrefix?: string;
  transferStartNumber?: number;
  nextTransferNumber?: number;
  payrollPrefix?: string;
  payrollStartNumber?: number;
  nextPayrollNumber?: number;
  reimbursementPrefix?: string;
  reimbursementStartNumber?: number;
  nextReimbursementNumber?: number;
  loanPrefix?: string;
  loanStartNumber?: number;
  nextLoanNumber?: number;
  employeePrefix?: string;
  employeeStartNumber?: number;
  nextEmployeeNumber?: number;
  contactPrefix?: string;
  contactStartNumber?: number;
  nextContactNumber?: number;
  bankAccountPrefix?: string;
  bankAccountStartNumber?: number;
  nextBankAccountNumber?: number;
  fixedAssetPrefix?: string;
  fixedAssetStartNumber?: number;
  nextFixedAssetNumber?: number;
  inventoryItemPrefix?: string;
  inventoryItemStartNumber?: number;
  nextInventoryItemNumber?: number;
  updatedAt: string;
};

export type UserPreferences = {
  id: string;
  userId: string;
  theme: "light" | "dark" | "system";
  density: "comfortable" | "compact";
  numberFormat: "id-ID" | "en-US";
  dateFormat: "DD/MM/YYYY" | "YYYY-MM-DD";
  createdAt: string;
  updatedAt: string;
};
